name = "tempfiles-js"
main = "src/router.js"
compatibility_date = "2022-08-29"
workers_dev = true
compatibility_flags = ["streams_enable_constructors"]

[[r2_buckets]]
binding = "R2"
bucket_name = "tempfiles"
preview_bucket_name = "tempfiles-preview"

[vars]
download_fqdn = "https://tmpfil.es"
file_expiration = 86400
server_ID = 1
